[build][build]

  command = "npm run build"  command = "npm run build"

  publish = "dist"  publish = "dist"



[[redirects]][[redirects]]

  from = "/*"  from = "/*"

  to = "/index.html"  to = "/index.html"

  status = 200  status = 200

  force = false  force = false



[[headers]][[headers]]

  for = "/*"  for = "/*"

  [headers.values]  [headers.values]

    X-Frame-Options = "DENY"    X-Frame-Options = "DENY"

    X-XSS-Protection = "1; mode=block"    X-XSS-Protection = "1; mode=block"

    X-Content-Type-Options = "nosniff"    X-Content-Type-Options = "nosniff"

